[tool.poetry]
name = "compiler"
version = "0.1.0"
description = ""
authors = ["Kanzu <kanzu32@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pysimplegui = "*"

[build-system]
requires = ["poetry-core", "pysimplegui"]
build-backend = "poetry.core.masonry.api"
